###

POST http://localhost:3000/api/add-player 
content-type: application/json

{
    "name": "monte",
    "rating": "1000"
}


###

PUT http://localhost:3000/api/set-winner/64edf6471d336655b055e813
content-type: application/json

{
    "winner": "Evil"
}

###
POST http://localhost:3000/api/new-game
Content-Type: application/json

{
    "players": [
        "blast",
        "capy",
        "rumelia",
        "youg",

        "ldp", 
        "curly",
        "monte",
        "nathan"
    ],
    "creator": "Samchy"
}
